# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kymo_pb2 as kymo__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kymo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KymoStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestMetrics = channel.stream_unary(
                '/kymo.Kymo/IngestMetrics',
                request_serializer=kymo__pb2.MetricsBatch.SerializeToString,
                response_deserializer=kymo__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestMetricsBidi = channel.stream_stream(
                '/kymo.Kymo/IngestMetricsBidi',
                request_serializer=kymo__pb2.MetricsBatch.SerializeToString,
                response_deserializer=kymo__pb2.IngestAck.FromString,
                _registered_method=True)
        self.PublishRichMutation = channel.unary_unary(
                '/kymo.Kymo/PublishRichMutation',
                request_serializer=kymo__pb2.PublishRichMutationRequest.SerializeToString,
                response_deserializer=kymo__pb2.PublishRichMutationResponse.FromString,
                _registered_method=True)
        self.InitRun = channel.unary_unary(
                '/kymo.Kymo/InitRun',
                request_serializer=kymo__pb2.InitRunRequest.SerializeToString,
                response_deserializer=kymo__pb2.InitRunResponse.FromString,
                _registered_method=True)
        self.RenameRun = channel.unary_unary(
                '/kymo.Kymo/RenameRun',
                request_serializer=kymo__pb2.RenameRunRequest.SerializeToString,
                response_deserializer=kymo__pb2.RenameRunResponse.FromString,
                _registered_method=True)
        self.TerminateRun = channel.unary_unary(
                '/kymo.Kymo/TerminateRun',
                request_serializer=kymo__pb2.TerminateRunRequest.SerializeToString,
                response_deserializer=kymo__pb2.TerminateRunResponse.FromString,
                _registered_method=True)
        self.ImportRun = channel.unary_unary(
                '/kymo.Kymo/ImportRun',
                request_serializer=kymo__pb2.ImportRunRequest.SerializeToString,
                response_deserializer=kymo__pb2.ImportRunResponse.FromString,
                _registered_method=True)
        self.ImportMetricsBidi = channel.stream_stream(
                '/kymo.Kymo/ImportMetricsBidi',
                request_serializer=kymo__pb2.MetricsBatch.SerializeToString,
                response_deserializer=kymo__pb2.IngestAck.FromString,
                _registered_method=True)
        self.FinalizeImportRun = channel.unary_unary(
                '/kymo.Kymo/FinalizeImportRun',
                request_serializer=kymo__pb2.FinalizeImportRunRequest.SerializeToString,
                response_deserializer=kymo__pb2.FinalizeImportRunResponse.FromString,
                _registered_method=True)
        self.TrashRuns = channel.unary_unary(
                '/kymo.Kymo/TrashRuns',
                request_serializer=kymo__pb2.TrashRunsRequest.SerializeToString,
                response_deserializer=kymo__pb2.TrashRunsResponse.FromString,
                _registered_method=True)
        self.RestoreRun = channel.unary_unary(
                '/kymo.Kymo/RestoreRun',
                request_serializer=kymo__pb2.RestoreRunRequest.SerializeToString,
                response_deserializer=kymo__pb2.RestoreRunResponse.FromString,
                _registered_method=True)
        self.ListTrash = channel.unary_unary(
                '/kymo.Kymo/ListTrash',
                request_serializer=kymo__pb2.ListTrashRequest.SerializeToString,
                response_deserializer=kymo__pb2.ListTrashResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/kymo.Kymo/GetRun',
                request_serializer=kymo__pb2.GetRunRequest.SerializeToString,
                response_deserializer=kymo__pb2.GetRunResponse.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/kymo.Kymo/ListProjects',
                request_serializer=kymo__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=kymo__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/kymo.Kymo/ListRuns',
                request_serializer=kymo__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=kymo__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.ListMetrics = channel.unary_unary(
                '/kymo.Kymo/ListMetrics',
                request_serializer=kymo__pb2.ListMetricsRequest.SerializeToString,
                response_deserializer=kymo__pb2.ListMetricsResponse.FromString,
                _registered_method=True)
        self.ListRunSetMetrics = channel.unary_unary(
                '/kymo.Kymo/ListRunSetMetrics',
                request_serializer=kymo__pb2.ListRunSetMetricsRequest.SerializeToString,
                response_deserializer=kymo__pb2.ListMetricsResponse.FromString,
                _registered_method=True)
        self.QueryChart = channel.unary_unary(
                '/kymo.Kymo/QueryChart',
                request_serializer=kymo__pb2.ChartRequest.SerializeToString,
                response_deserializer=kymo__pb2.ChartResponse.FromString,
                _registered_method=True)
        self.QueryCdnKeys = channel.unary_unary(
                '/kymo.Kymo/QueryCdnKeys',
                request_serializer=kymo__pb2.QueryCdnKeysRequest.SerializeToString,
                response_deserializer=kymo__pb2.QueryCdnKeysResponse.FromString,
                _registered_method=True)
        self.QueryTextWindow = channel.unary_unary(
                '/kymo.Kymo/QueryTextWindow',
                request_serializer=kymo__pb2.QueryTextWindowRequest.SerializeToString,
                response_deserializer=kymo__pb2.QueryTextWindowResponse.FromString,
                _registered_method=True)
        self.PollVersions = channel.unary_unary(
                '/kymo.Kymo/PollVersions',
                request_serializer=kymo__pb2.PollVersionsRequest.SerializeToString,
                response_deserializer=kymo__pb2.PollVersionsResponse.FromString,
                _registered_method=True)


class KymoServicer:
    """Missing associated documentation comment in .proto file."""

    def IngestMetrics(self, request_iterator, context):
        """--- Ingest ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestMetricsBidi(self, request_iterator, context):
        """Pipelined ingest: server acks cumulatively as bounded flush cuts commit
        (normally 10k rows or about 8 MiB, plus timer/half-close tails), so the
        cut — not the whole call — is the durability/retry unit. Unary
        IngestMetrics stays for CDN sends, simple callers, and kymo.sync replay.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishRichMutation(self, request, context):
        """Ordered publication for rich CDN-backed values. Kept separate from the
        high-throughput stream so numeric ingest retains its acknowledgement
        contract.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitRun(self, request, context):
        """--- Run registration ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportRun(self, request, context):
        """--- Bulk import (historical replay) ---
        FAILED_PRECONDITION unless the server runs with KYMO_IMPORT_ENABLED=1.
        ImportRun backdates runs.created_at; ImportMetricsBidi has the live wire
        contract (cumulative position acks, ack = committed) on a private insert
        budget; FinalizeImportRun backdates the terminal state and registers the
        metric names the import actually wrote.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportMetricsBidi(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeImportRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrashRuns(self, request, context):
        """--- Run lifecycle / Trash ---
        TrashRuns has no public batch-size limit. The server may split work into
        bounded internal transactions and reports an outcome for every input
        position, so callers can reconcile partial success safely.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """--- Discovery ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunSetMetrics(self, request, context):
        """Discovery for a SET of runs in one round trip: distinct metric names
        across run_ids, types collapsed by CDN < NUMERIC < TEXT_STREAM.
        Replaces the dashboard sweeping ListMetrics over every run and
        unioning client-side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryChart(self, request, context):
        """--- Chart queries (replaces QueryMetrics) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryCdnKeys(self, request, context):
        """--- CDN queries ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTextWindow(self, request, context):
        """Line-oriented window for virtualized log viewers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollVersions(self, request, context):
        """--- Change detection ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KymoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestMetrics': grpc.stream_unary_rpc_method_handler(
                    servicer.IngestMetrics,
                    request_deserializer=kymo__pb2.MetricsBatch.FromString,
                    response_serializer=kymo__pb2.IngestResponse.SerializeToString,
            ),
            'IngestMetricsBidi': grpc.stream_stream_rpc_method_handler(
                    servicer.IngestMetricsBidi,
                    request_deserializer=kymo__pb2.MetricsBatch.FromString,
                    response_serializer=kymo__pb2.IngestAck.SerializeToString,
            ),
            'PublishRichMutation': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishRichMutation,
                    request_deserializer=kymo__pb2.PublishRichMutationRequest.FromString,
                    response_serializer=kymo__pb2.PublishRichMutationResponse.SerializeToString,
            ),
            'InitRun': grpc.unary_unary_rpc_method_handler(
                    servicer.InitRun,
                    request_deserializer=kymo__pb2.InitRunRequest.FromString,
                    response_serializer=kymo__pb2.InitRunResponse.SerializeToString,
            ),
            'RenameRun': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameRun,
                    request_deserializer=kymo__pb2.RenameRunRequest.FromString,
                    response_serializer=kymo__pb2.RenameRunResponse.SerializeToString,
            ),
            'TerminateRun': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateRun,
                    request_deserializer=kymo__pb2.TerminateRunRequest.FromString,
                    response_serializer=kymo__pb2.TerminateRunResponse.SerializeToString,
            ),
            'ImportRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportRun,
                    request_deserializer=kymo__pb2.ImportRunRequest.FromString,
                    response_serializer=kymo__pb2.ImportRunResponse.SerializeToString,
            ),
            'ImportMetricsBidi': grpc.stream_stream_rpc_method_handler(
                    servicer.ImportMetricsBidi,
                    request_deserializer=kymo__pb2.MetricsBatch.FromString,
                    response_serializer=kymo__pb2.IngestAck.SerializeToString,
            ),
            'FinalizeImportRun': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeImportRun,
                    request_deserializer=kymo__pb2.FinalizeImportRunRequest.FromString,
                    response_serializer=kymo__pb2.FinalizeImportRunResponse.SerializeToString,
            ),
            'TrashRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.TrashRuns,
                    request_deserializer=kymo__pb2.TrashRunsRequest.FromString,
                    response_serializer=kymo__pb2.TrashRunsResponse.SerializeToString,
            ),
            'RestoreRun': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreRun,
                    request_deserializer=kymo__pb2.RestoreRunRequest.FromString,
                    response_serializer=kymo__pb2.RestoreRunResponse.SerializeToString,
            ),
            'ListTrash': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrash,
                    request_deserializer=kymo__pb2.ListTrashRequest.FromString,
                    response_serializer=kymo__pb2.ListTrashResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=kymo__pb2.GetRunRequest.FromString,
                    response_serializer=kymo__pb2.GetRunResponse.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=kymo__pb2.ListProjectsRequest.FromString,
                    response_serializer=kymo__pb2.ListProjectsResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=kymo__pb2.ListRunsRequest.FromString,
                    response_serializer=kymo__pb2.ListRunsResponse.SerializeToString,
            ),
            'ListMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMetrics,
                    request_deserializer=kymo__pb2.ListMetricsRequest.FromString,
                    response_serializer=kymo__pb2.ListMetricsResponse.SerializeToString,
            ),
            'ListRunSetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunSetMetrics,
                    request_deserializer=kymo__pb2.ListRunSetMetricsRequest.FromString,
                    response_serializer=kymo__pb2.ListMetricsResponse.SerializeToString,
            ),
            'QueryChart': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryChart,
                    request_deserializer=kymo__pb2.ChartRequest.FromString,
                    response_serializer=kymo__pb2.ChartResponse.SerializeToString,
            ),
            'QueryCdnKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCdnKeys,
                    request_deserializer=kymo__pb2.QueryCdnKeysRequest.FromString,
                    response_serializer=kymo__pb2.QueryCdnKeysResponse.SerializeToString,
            ),
            'QueryTextWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTextWindow,
                    request_deserializer=kymo__pb2.QueryTextWindowRequest.FromString,
                    response_serializer=kymo__pb2.QueryTextWindowResponse.SerializeToString,
            ),
            'PollVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.PollVersions,
                    request_deserializer=kymo__pb2.PollVersionsRequest.FromString,
                    response_serializer=kymo__pb2.PollVersionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kymo.Kymo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kymo.Kymo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kymo:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kymo.Kymo/IngestMetrics',
            kymo__pb2.MetricsBatch.SerializeToString,
            kymo__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestMetricsBidi(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kymo.Kymo/IngestMetricsBidi',
            kymo__pb2.MetricsBatch.SerializeToString,
            kymo__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishRichMutation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/PublishRichMutation',
            kymo__pb2.PublishRichMutationRequest.SerializeToString,
            kymo__pb2.PublishRichMutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/InitRun',
            kymo__pb2.InitRunRequest.SerializeToString,
            kymo__pb2.InitRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/RenameRun',
            kymo__pb2.RenameRunRequest.SerializeToString,
            kymo__pb2.RenameRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/TerminateRun',
            kymo__pb2.TerminateRunRequest.SerializeToString,
            kymo__pb2.TerminateRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/ImportRun',
            kymo__pb2.ImportRunRequest.SerializeToString,
            kymo__pb2.ImportRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportMetricsBidi(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kymo.Kymo/ImportMetricsBidi',
            kymo__pb2.MetricsBatch.SerializeToString,
            kymo__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeImportRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/FinalizeImportRun',
            kymo__pb2.FinalizeImportRunRequest.SerializeToString,
            kymo__pb2.FinalizeImportRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrashRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/TrashRuns',
            kymo__pb2.TrashRunsRequest.SerializeToString,
            kymo__pb2.TrashRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/RestoreRun',
            kymo__pb2.RestoreRunRequest.SerializeToString,
            kymo__pb2.RestoreRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/ListTrash',
            kymo__pb2.ListTrashRequest.SerializeToString,
            kymo__pb2.ListTrashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/GetRun',
            kymo__pb2.GetRunRequest.SerializeToString,
            kymo__pb2.GetRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/ListProjects',
            kymo__pb2.ListProjectsRequest.SerializeToString,
            kymo__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/ListRuns',
            kymo__pb2.ListRunsRequest.SerializeToString,
            kymo__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/ListMetrics',
            kymo__pb2.ListMetricsRequest.SerializeToString,
            kymo__pb2.ListMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunSetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/ListRunSetMetrics',
            kymo__pb2.ListRunSetMetricsRequest.SerializeToString,
            kymo__pb2.ListMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/QueryChart',
            kymo__pb2.ChartRequest.SerializeToString,
            kymo__pb2.ChartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryCdnKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/QueryCdnKeys',
            kymo__pb2.QueryCdnKeysRequest.SerializeToString,
            kymo__pb2.QueryCdnKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTextWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/QueryTextWindow',
            kymo__pb2.QueryTextWindowRequest.SerializeToString,
            kymo__pb2.QueryTextWindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.Kymo/PollVersions',
            kymo__pb2.PollVersionsRequest.SerializeToString,
            kymo__pb2.PollVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WatchdogServiceStub:
    """=== Watchdog ===

    The kymo-watchdog service maintains a best-effort low-latency view of
    active runs and emits state-transition hints to downstream consumers.
    ListRuns polling is authoritative for current state; this service is not a
    durable or exactly-once lifecycle event log.

    Server -> watchdog notifications are at-most-once, fire-and-forget hints for
    explicit lifecycle events only (created, terminated, or restored). Trash
    removal is reconciled from the authoritative ListRuns snapshot instead of
    emitting one event per run in an uncapped bulk operation.
    Derived state transitions (RUNNING -> STUCK -> UNRESPONSIVE -> PRESUMED_DEAD)
    are NOT pushed here — the watchdog discovers those by polling ListRuns at
    a fixed interval for the projects whose runs it is tracking.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyRunLifecycle = channel.unary_unary(
                '/kymo.WatchdogService/NotifyRunLifecycle',
                request_serializer=kymo__pb2.RunLifecycleEvent.SerializeToString,
                response_deserializer=kymo__pb2.RunLifecycleAck.FromString,
                _registered_method=True)


class WatchdogServiceServicer:
    """=== Watchdog ===

    The kymo-watchdog service maintains a best-effort low-latency view of
    active runs and emits state-transition hints to downstream consumers.
    ListRuns polling is authoritative for current state; this service is not a
    durable or exactly-once lifecycle event log.

    Server -> watchdog notifications are at-most-once, fire-and-forget hints for
    explicit lifecycle events only (created, terminated, or restored). Trash
    removal is reconciled from the authoritative ListRuns snapshot instead of
    emitting one event per run in an uncapped bulk operation.
    Derived state transitions (RUNNING -> STUCK -> UNRESPONSIVE -> PRESUMED_DEAD)
    are NOT pushed here — the watchdog discovers those by polling ListRuns at
    a fixed interval for the projects whose runs it is tracking.

    """

    def NotifyRunLifecycle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchdogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyRunLifecycle': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyRunLifecycle,
                    request_deserializer=kymo__pb2.RunLifecycleEvent.FromString,
                    response_serializer=kymo__pb2.RunLifecycleAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kymo.WatchdogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kymo.WatchdogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchdogService:
    """=== Watchdog ===

    The kymo-watchdog service maintains a best-effort low-latency view of
    active runs and emits state-transition hints to downstream consumers.
    ListRuns polling is authoritative for current state; this service is not a
    durable or exactly-once lifecycle event log.

    Server -> watchdog notifications are at-most-once, fire-and-forget hints for
    explicit lifecycle events only (created, terminated, or restored). Trash
    removal is reconciled from the authoritative ListRuns snapshot instead of
    emitting one event per run in an uncapped bulk operation.
    Derived state transitions (RUNNING -> STUCK -> UNRESPONSIVE -> PRESUMED_DEAD)
    are NOT pushed here — the watchdog discovers those by polling ListRuns at
    a fixed interval for the projects whose runs it is tracking.

    """

    @staticmethod
    def NotifyRunLifecycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kymo.WatchdogService/NotifyRunLifecycle',
            kymo__pb2.RunLifecycleEvent.SerializeToString,
            kymo__pb2.RunLifecycleAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
